# Generated by Django 5.2.4 on 2025-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_url', models.URLField()),
                ('upload_date', models.DateField()),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_coach.human_coach')),
            ],
        ),
    ]
