# Generated by Django 5.2.4 on 2025-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion_data',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion', models.CharField(max_length=50)),
                ('intensity', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_log.session_log')),
            ],
        ),
    ]
