# Generated by Django 6.0 on 2025-12-19 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion_data',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
