# Generated by Django 6.0.2 on 2026-04-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_age'),
        ('emotion_data', '0002_emotion_data_created_at_emotion_data_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_emotion', models.CharField(help_text='Latest emotion from emotion_data', max_length=50)),
                ('raw_intensity', models.IntegerField(help_text='Latest intensity from emotion_data')),
                ('final_emotion', models.CharField(help_text='Ollama-analyzed dominant emotion', max_length=50)),
                ('final_intensity', models.IntegerField(help_text='Refined intensity (1-10)')),
                ('recommendation', models.TextField(help_text='AI-generated recommendation based on emotion trends')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in assessment (0-1)')),
                ('emotions_analyzed', models.TextField(help_text='JSON string of 10 emotions analyzed')),
                ('journal_entry', models.TextField(blank=True, help_text='Journal entry used in analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'verbose_name': 'Final Assessment',
                'verbose_name_plural': 'Final Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
