# Generated by Django 6.0 on 2026-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_log',
            name='emotion_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_log',
            name='final_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session_log',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
