# Generated by Django 6.0 on 2026-01-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0002_session_log_emotion_intensity_and_more'),
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_log',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session_log',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
