# Generated by Django 6.0.2 on 2026-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0003_alter_session_log_notes_alter_session_log_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_log',
            name='coach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session_log',
            name='highest_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_log',
            name='needs_human_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session_log',
            name='referral_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session_log',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
