# Generated by Django 6.0.2 on 2026-03-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_age'),
        ('emotion_data', '0002_emotion_data_created_at_emotion_data_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('emotion_alert', 'Emotion Alert'), ('session_summary', 'Session Summary'), ('wellness_tip', 'Wellness Tip'), ('ai_suggestion', 'AI Suggestion')], default='ai_suggestion', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('emotion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotion_data.emotion_data')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
