# Generated by Django 6.0.2 on 2026-05-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_coach', '0002_human_coach_approved_at_human_coach_is_approved_and_more'),
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_coach',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='user.user'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.JSONField(default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_coach.human_coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='user.user')),
            ],
        ),
    ]
