# Generated by Django 5.2.4 on 2025-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('human_coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach_client',
            fields=[
                ('coach_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_coach.human_coach')),
            ],
        ),
    ]
