# Generated by Django 6.0.2 on 2026-05-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_age'),
        ('coach_client', '0001_initial'),
        ('human_coach', '0003_alter_human_coach_user_id_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='client.client')),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='human_coach.human_coach')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
