# Generated by Django 5.2.4 on 2025-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_coach', '0001_initial'),
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_coach.human_coach')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_log.session_log')),
            ],
        ),
    ]
