# Generated by Django 5.2.4 on 2025-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotion_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_guidance',
            fields=[
                ('guidance_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.TextField()),
                ('effectiveness', models.IntegerField()),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion_data.emotion_data')),
            ],
        ),
    ]
