# Generated by Django 6.0 on 2025-12-19 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_guidance',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai_guidance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ai_guidance',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ai_guidance',
            name='effectiveness',
            field=models.IntegerField(default=0),
        ),
    ]
