# Generated by Django 6.0 on 2025-12-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_guidance', '0002_ai_guidance_ai_response_ai_guidance_created_at_and_more'),
        ('client', '0001_initial'),
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_guidance',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='ai_guidance',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session_log.session_log'),
        ),
    ]
