# Generated by Django 6.0.2 on 2026-03-07 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_guidance', '0003_ai_guidance_client_id_ai_guidance_session_id'),
        ('client', '0002_alter_client_age'),
        ('session_log', '0003_alter_session_log_notes_alter_session_log_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response')], max_length=10)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.client')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='session_log.session_log')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_message_count', models.IntegerField(default=0)),
                ('ai_message_count', models.IntegerField(default=0)),
                ('session_duration', models.IntegerField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('average_intensity', models.FloatField(blank=True, null=True)),
                ('emotion_transition_count', models.IntegerField(default=0)),
                ('emotional_range', models.JSONField(blank=True, null=True)),
                ('average_sentiment', models.FloatField(blank=True, null=True)),
                ('sentiment_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('alliance_score', models.FloatField(blank=True, null=True)),
                ('engagement_level', models.CharField(blank=True, max_length=20, null=True)),
                ('max_risk_level', models.CharField(default='low', max_length=20)),
                ('crisis_flags', models.IntegerField(default=0)),
                ('coping_strategies_mentioned', models.IntegerField(default=0)),
                ('positive_reframing_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('session_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='session_log.session_log')),
            ],
        ),
        migrations.CreateModel(
            name='MessageEmotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_emotion', models.CharField(max_length=50)),
                ('emotion_confidence', models.FloatField()),
                ('intensity', models.IntegerField()),
                ('secondary_emotions', models.JSONField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('crisis_keywords', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='ai_guidance.chatmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', 'timestamp'], name='ai_guidance_session_ad921d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['client_id', 'timestamp'], name='ai_guidance_client__7b7f65_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['client_id', 'created_at'], name='ai_guidance_client__a7e832_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['max_risk_level'], name='ai_guidance_max_ris_d0d000_idx'),
        ),
        migrations.AddIndex(
            model_name='messageemotion',
            index=models.Index(fields=['primary_emotion'], name='ai_guidance_primary_2a19ee_idx'),
        ),
        migrations.AddIndex(
            model_name='messageemotion',
            index=models.Index(fields=['risk_level'], name='ai_guidance_risk_le_cc9b26_idx'),
        ),
    ]
