# Generated by Django 6.0 on 2026-01-04 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=255, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
